### ISSUE TITLE
[public report]: server error when viewing rewards

### ISSUE THREAD

**Issue by Kaizen-Step** [MetricsDAO/xyz#631]
### User Impacted

0xd32F163205911bC28D91AaeFB8d0cABC0BA0Cb53

### Discord ID (including number)

Ludwig.1989#2740

### Workflow Impacted

My Rewards

### Feature Impacted

Claim Reward

### Issue description

I don't know if it's too late or not. and whether you are still in the beta phase. I just want to share my experience roaming the app. I had no chance to submit or review a dashboard because the deadline passed 10 days ago, but when I tried to select a reward token from the rewards tab, I encountered a server error.

### Blocking

yes it is

### Relevant log output

```shell
Error: Unexpected Server Error
    at handleDataRequestRR (/myapp/build/server.js:38908:35)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
    at requestHandler (/myapp/build/server.js:38838:22)
    at /myapp/build/server.js:40008:26
```

**Comment by gnomadic** [comment]
@bcinman do we have this crash in sentry?

**Comment by Kaizen-Step** [comment]
I still face the same error in the same circumstances :

Error: Unexpected Server Error
    at handleDataRequestRR (/var/task/node_modules/@remix-run/server-runtime/dist/server.js:128:31)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
    at requestHandler (/var/task/node_modules/@remix-run/server-runtime/dist/server.js:55:18)
    at Server.default (file:///var/task/build/server-build-nodejs-eyJydW50aW1lIjoibm9kZWpzIn0.mjs:74:20)

**Comment by Kaizen-Step** [comment]
I also encountered a system error after submitting my dashboard, the functionality was ok (the dashboard was submitted), but the following error pops up.

![Server Error](https://user-images.githubusercontent.com/121562702/230862161-d9e57fbf-54e9-4fa9-a6ab-c57a965785b4.jpg)

**Comment by gnomadic** [comment]
Fix is in review: https://github.com/MetricsDAO/xyz/pull/801
