### ISSUE TITLE
Prereqs Tab crashes

### ISSUE THREAD

**Issue by gnomadic** [MetricsDAO/xyz#711]
TypeError: Cannot read properties of null (reading 'crumbs')
    at Q (https://metricsdao.xyz/build/routes/app+/market_.$address.request.$requestId-PTD4IWDG.js:1:3020)
    at du (https://metricsdao.xyz/build/_shared/chunk-26UEVSQP.js:6:19484)
    at _i (https://metricsdao.xyz/build/_shared/chunk-26UEVSQP.js:8:3153)
    at Ba (https://metricsdao.xyz/build/_shared/chunk-26UEVSQP.js:8:44792)
    at Ua (https://metricsdao.xyz/build/_shared/chunk-26UEVSQP.js:8:39724)
    at Vf (https://metricsdao.xyz/build/_shared/chunk-26UEVSQP.js:8:39655)
    at qr (https://metricsdao.xyz/build/_shared/chunk-26UEVSQP.js:8:39515)
    at Ii (https://metricsdao.xyz/build/_shared/chunk-26UEVSQP.js:8:35905)
    at Qo (https://metricsdao.xyz/build/_shared/chunk-26UEVSQP.js:8:36715)
    at pn (https://metricsdao.xyz/build/_shared/chunk-26UEVSQP.js:6:3250)
    at https://metricsdao.xyz/build/_shared/chunk-26UEVSQP.js:8:34235

**Comment by sebruiz** [comment]
We reverted the PR causing this issue
https://github.com/MetricsDAO/xyz/pull/712

Going to close
