### ISSUE TITLE
[public report]: 

### ISSUE THREAD

**Issue by davidenoch** [MetricsDAO/xyz#723]
### User Impacted

0x51062AF21E68007edfa5D4f8c19B59DeF76aBF4c

### Discord ID (including number)

potmo#9983

### Workflow Impacted

Analyze

### Feature Impacted

Score Submission

### Issue description

As far as I can tell, I was able to claim ten reviews. Yesterday, I reviewed one bounty, and submitted it, but I couldn't see any verification anywhere, as to whether or not my review was even counted.
Today, I started another review I got the message I received below. I wanted to report this right away, so, as of now, yes it is preventing me from completing my work. 

### Blocking

yes it is

### Relevant log output

```shell
Application Error
TypeError: Cannot read properties of undefined (reading 'ScalableLikertEnforcement')
    at y (https://metricsdao.xyz/build/_shared/chunk-QOXIIKED.js:1:327)
    at Oe (https://metricsdao.xyz/build/routes/app+/market_.$address.submission.$submissionId-DL733LYF.js:1:8832)
    at du (https://metricsdao.xyz/build/_shared/chunk-26UEVSQP.js:6:19484)
    at _i (https://metricsdao.xyz/build/_shared/chunk-26UEVSQP.js:8:3153)
    at Ba (https://metricsdao.xyz/build/_shared/chunk-26UEVSQP.js:8:44792)
    at Ua (https://metricsdao.xyz/build/_shared/chunk-26UEVSQP.js:8:39724)
    at Vf (https://metricsdao.xyz/build/_shared/chunk-26UEVSQP.js:8:39655)
    at qr (https://metricsdao.xyz/build/_shared/chunk-26UEVSQP.js:8:39515)
    at Ii (https://metricsdao.xyz/build/_shared/chunk-26UEVSQP.js:8:35905)
    at Qo (https://metricsdao.xyz/build/_shared/chunk-26UEVSQP.js:8:36715)
    at pn (https://metricsdao.xyz/build/_shared/chunk-26UEVSQP.js:6:3250)
    at https://metricsdao.xyz/build/_shared/chunk-26UEVSQP.js:8:34235
```

**Comment by davidenoch** [comment]
turned on and off or something and now it works :-)
