### ISSUE TITLE
[public report]: 

### ISSUE THREAD

**Issue by ZSaed** [MetricsDAO/xyz#799]
### User Impacted

0x61F6ff4aC3FC2e266F8FEF45b28717dcDE5cB6af

### Discord ID (including number)

ZSaed#2204

### Workflow Impacted

My Rewards

### Feature Impacted

Claim Reward

### Issue description

Issue Description
Hi 
I am currently facing with the reward page. Whenever I attempt to access it, I encounter an error message that prevents me from viewing my reward list. Interestingly, I tried accessing the reward page with a different wallet, and it worked perfectly fine. However, the error persists when I use my original wallet.

### Blocking

yes it is

### Relevant log output

```shell
Error 1: 
Application Error
Error: Unexpected Server Error
    at handleDataRequestRR (/myapp/build/server.js:38908:35)
    at requestHandler (/myapp/build/server.js:38838:22)
    at /myapp/build/server.js:40008:26

After refreshing the error page i get the following error: 
Application Error
Error: 
Invalid `prisma.reward.createMany()` invocation:


Unique constraint failed on the constraint: `Reward_laborMarketAddress_submissionId_key`
    at pn.handleRequestError (/myapp/node_modules/@prisma/client/runtime/library.js:176:6477)
    at pn.handleAndLogRequestError (/myapp/node_modules/@prisma/client/runtime/library.js:176:5907)
    at pn.request (/myapp/node_modules/@prisma/client/runtime/library.js:176:5786)
    at t._request (/myapp/node_modules/@prisma/client/runtime/library.js:179:10484)
    at createRewards (/myapp/build/index.js:15812:3)
    at synchronizeRewards (/myapp/build/index.js:15861:3)
    at getSubmissionWithRewards (/myapp/build/index.js:15921:10)
    at loader30 (/myapp/build/index.js:20137:78)
    at /myapp/build/server.js:71337:17
    at Object.callRouteLoaderRR (/myapp/build/server.js:38660:20)
```

**Comment by sebruiz** [comment]
@ZSaed can you see if it loads now?

**Comment by ZSaed** [comment]
> 
still i get the same error

**Comment by ZSaed** [comment]
> > > 
> > 
> > 
> > still i get the same error
> 
> sorry @ZSaed, missed a change. How about _now_?


Unfortunately I still get the Error. I try it on the three different browser(chrome, firefox and brave) also I delete the cookie and empty the cache but still not working.

**Comment by ZSaed** [comment]
thanks now i can see my reward.
